--liquibase formatted sql

--changeset timattt:1

create table example_user(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL,

    PRIMARY KEY (user_id)
);